steps:
  - name: node
    entrypoint: npm
    args: ['install']

  # Build with .env
  - name: node
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'PORT=${_PORT}'
      - 'PROJECT_ID=${_PROJECT_ID}'
      - 'DB_HOST=${_DB_HOST}'
      - 'DB_USER=${_DB_USER}'
      - 'DB_PASSWORD=${_DB_PASSWORD}'
      - 'DB_DATABASE=${_DB_DATABASE}'
      - 'DB_PORT=${_DB_PORT}'

  # Build the container image
  - name: gcr.io/cloud-builders/docker
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}', '.']
    id: Building the container image

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']
    id: Pushing the image to registry

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}',
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]
